//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region Métadonnées de relation EDM

[assembly: EdmRelationshipAttribute("Projet2Model", "FK__construct__codeP__0DAF0CB0", "ficheProjet", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Projet.ficheProjet), "construction", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Projet.construction), true)]
[assembly: EdmRelationshipAttribute("Projet2Model", "FK__foncier__codePro__08EA5793", "ficheProjet", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Projet.ficheProjet), "foncier", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Projet.foncier), true)]
[assembly: EdmRelationshipAttribute("Projet2Model", "FK__resultat__codePr__3B75D760", "ficheProjet", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Projet.ficheProjet), "resultat", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Projet.resultat), true)]
[assembly: EdmRelationshipAttribute("Projet2Model", "FK__viabilisa__codeP__1273C1CD", "ficheProjet", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Projet.ficheProjet), "viabilisation", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Projet.viabilisation), true)]

#endregion

namespace Projet
{
    #region Contextes
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    public partial class Projet2Entities1 : ObjectContext
    {
        #region Constructeurs
    
        /// <summary>
        /// Initialise un nouvel objet Projet2Entities1 à l'aide de la chaîne de connexion trouvée dans la section 'Projet2Entities1' du fichier de configuration d'application.
        /// </summary>
        public Projet2Entities1() : base("name=Projet2Entities1", "Projet2Entities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisez un nouvel objet Projet2Entities1.
        /// </summary>
        public Projet2Entities1(string connectionString) : base(connectionString, "Projet2Entities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisez un nouvel objet Projet2Entities1.
        /// </summary>
        public Projet2Entities1(EntityConnection connection) : base(connection, "Projet2Entities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Méthodes partielles
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propriétés ObjectSet
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<construction> construction
        {
            get
            {
                if ((_construction == null))
                {
                    _construction = base.CreateObjectSet<construction>("construction");
                }
                return _construction;
            }
        }
        private ObjectSet<construction> _construction;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<ficheProjet> ficheProjet
        {
            get
            {
                if ((_ficheProjet == null))
                {
                    _ficheProjet = base.CreateObjectSet<ficheProjet>("ficheProjet");
                }
                return _ficheProjet;
            }
        }
        private ObjectSet<ficheProjet> _ficheProjet;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<foncier> foncier
        {
            get
            {
                if ((_foncier == null))
                {
                    _foncier = base.CreateObjectSet<foncier>("foncier");
                }
                return _foncier;
            }
        }
        private ObjectSet<foncier> _foncier;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<resultat> resultat
        {
            get
            {
                if ((_resultat == null))
                {
                    _resultat = base.CreateObjectSet<resultat>("resultat");
                }
                return _resultat;
            }
        }
        private ObjectSet<resultat> _resultat;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<sysdiagrams> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagrams>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagrams> _sysdiagrams;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<Users> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<Users>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<Users> _Users;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<viabilisation> viabilisation
        {
            get
            {
                if ((_viabilisation == null))
                {
                    _viabilisation = base.CreateObjectSet<viabilisation>("viabilisation");
                }
                return _viabilisation;
            }
        }
        private ObjectSet<viabilisation> _viabilisation;

        #endregion

        #region Méthodes AddTo
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet construction. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToconstruction(construction construction)
        {
            base.AddObject("construction", construction);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet ficheProjet. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToficheProjet(ficheProjet ficheProjet)
        {
            base.AddObject("ficheProjet", ficheProjet);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet foncier. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddTofoncier(foncier foncier)
        {
            base.AddObject("foncier", foncier);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet resultat. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToresultat(resultat resultat)
        {
            base.AddObject("resultat", resultat);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet sysdiagrams. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddTosysdiagrams(sysdiagrams sysdiagrams)
        {
            base.AddObject("sysdiagrams", sysdiagrams);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet Users. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToUsers(Users users)
        {
            base.AddObject("Users", users);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet viabilisation. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToviabilisation(viabilisation viabilisation)
        {
            base.AddObject("viabilisation", viabilisation);
        }

        #endregion

    }

    #endregion

    #region Entités
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Projet2Model", Name="construction")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class construction : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet construction.
        /// </summary>
        /// <param name="numconstruction">Valeur initiale de la propriété numconstruction.</param>
        public static construction Createconstruction(global::System.Int32 numconstruction)
        {
            construction construction = new construction();
            construction.numconstruction = numconstruction;
            return construction;
        }

        #endregion

        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 numconstruction
        {
            get
            {
                return _numconstruction;
            }
            set
            {
                if (_numconstruction != value)
                {
                    OnnumconstructionChanging(value);
                    ReportPropertyChanging("numconstruction");
                    _numconstruction = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("numconstruction");
                    OnnumconstructionChanged();
                }
            }
        }
        private global::System.Int32 _numconstruction;
        partial void OnnumconstructionChanging(global::System.Int32 value);
        partial void OnnumconstructionChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> constructionLogSoc
        {
            get
            {
                return _constructionLogSoc;
            }
            set
            {
                OnconstructionLogSocChanging(value);
                ReportPropertyChanging("constructionLogSoc");
                _constructionLogSoc = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("constructionLogSoc");
                OnconstructionLogSocChanged();
            }
        }
        private Nullable<global::System.Double> _constructionLogSoc;
        partial void OnconstructionLogSocChanging(Nullable<global::System.Double> value);
        partial void OnconstructionLogSocChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> contructionEqP1
        {
            get
            {
                return _contructionEqP1;
            }
            set
            {
                OncontructionEqP1Changing(value);
                ReportPropertyChanging("contructionEqP1");
                _contructionEqP1 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("contructionEqP1");
                OncontructionEqP1Changed();
            }
        }
        private Nullable<global::System.Double> _contructionEqP1;
        partial void OncontructionEqP1Changing(Nullable<global::System.Double> value);
        partial void OncontructionEqP1Changed();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> contructionEqP2
        {
            get
            {
                return _contructionEqP2;
            }
            set
            {
                OncontructionEqP2Changing(value);
                ReportPropertyChanging("contructionEqP2");
                _contructionEqP2 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("contructionEqP2");
                OncontructionEqP2Changed();
            }
        }
        private Nullable<global::System.Double> _contructionEqP2;
        partial void OncontructionEqP2Changing(Nullable<global::System.Double> value);
        partial void OncontructionEqP2Changed();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> codeProjet
        {
            get
            {
                return _codeProjet;
            }
            set
            {
                OncodeProjetChanging(value);
                ReportPropertyChanging("codeProjet");
                _codeProjet = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("codeProjet");
                OncodeProjetChanged();
            }
        }
        private Nullable<global::System.Int32> _codeProjet;
        partial void OncodeProjetChanging(Nullable<global::System.Int32> value);
        partial void OncodeProjetChanged();

        #endregion

    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Projet2Model", "FK__construct__codeP__0DAF0CB0", "ficheProjet")]
        public ficheProjet ficheProjet
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ficheProjet>("Projet2Model.FK__construct__codeP__0DAF0CB0", "ficheProjet").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ficheProjet>("Projet2Model.FK__construct__codeP__0DAF0CB0", "ficheProjet").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ficheProjet> ficheProjetReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ficheProjet>("Projet2Model.FK__construct__codeP__0DAF0CB0", "ficheProjet");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ficheProjet>("Projet2Model.FK__construct__codeP__0DAF0CB0", "ficheProjet", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Projet2Model", Name="ficheProjet")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ficheProjet : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet ficheProjet.
        /// </summary>
        /// <param name="codeProjet">Valeur initiale de la propriété codeProjet.</param>
        public static ficheProjet CreateficheProjet(global::System.Int32 codeProjet)
        {
            ficheProjet ficheProjet = new ficheProjet();
            ficheProjet.codeProjet = codeProjet;
            return ficheProjet;
        }

        #endregion

        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 codeProjet
        {
            get
            {
                return _codeProjet;
            }
            set
            {
                if (_codeProjet != value)
                {
                    OncodeProjetChanging(value);
                    ReportPropertyChanging("codeProjet");
                    _codeProjet = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("codeProjet");
                    OncodeProjetChanged();
                }
            }
        }
        private global::System.Int32 _codeProjet;
        partial void OncodeProjetChanging(global::System.Int32 value);
        partial void OncodeProjetChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String typeLogement
        {
            get
            {
                return _typeLogement;
            }
            set
            {
                OntypeLogementChanging(value);
                ReportPropertyChanging("typeLogement");
                _typeLogement = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("typeLogement");
                OntypeLogementChanged();
            }
        }
        private global::System.String _typeLogement;
        partial void OntypeLogementChanging(global::System.String value);
        partial void OntypeLogementChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> ouvrageAcc
        {
            get
            {
                return _ouvrageAcc;
            }
            set
            {
                OnouvrageAccChanging(value);
                ReportPropertyChanging("ouvrageAcc");
                _ouvrageAcc = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ouvrageAcc");
                OnouvrageAccChanged();
            }
        }
        private Nullable<global::System.Double> _ouvrageAcc;
        partial void OnouvrageAccChanging(Nullable<global::System.Double> value);
        partial void OnouvrageAccChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> terrain
        {
            get
            {
                return _terrain;
            }
            set
            {
                OnterrainChanging(value);
                ReportPropertyChanging("terrain");
                _terrain = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("terrain");
                OnterrainChanged();
            }
        }
        private Nullable<global::System.Double> _terrain;
        partial void OnterrainChanging(Nullable<global::System.Double> value);
        partial void OnterrainChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> referanceTerrain
        {
            get
            {
                return _referanceTerrain;
            }
            set
            {
                OnreferanceTerrainChanging(value);
                ReportPropertyChanging("referanceTerrain");
                _referanceTerrain = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("referanceTerrain");
                OnreferanceTerrainChanged();
            }
        }
        private Nullable<global::System.Double> _referanceTerrain;
        partial void OnreferanceTerrainChanging(Nullable<global::System.Double> value);
        partial void OnreferanceTerrainChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> zone
        {
            get
            {
                return _zone;
            }
            set
            {
                OnzoneChanging(value);
                ReportPropertyChanging("zone");
                _zone = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("zone");
                OnzoneChanged();
            }
        }
        private Nullable<global::System.Double> _zone;
        partial void OnzoneChanging(Nullable<global::System.Double> value);
        partial void OnzoneChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String distinction
        {
            get
            {
                return _distinction;
            }
            set
            {
                OndistinctionChanging(value);
                ReportPropertyChanging("distinction");
                _distinction = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("distinction");
                OndistinctionChanged();
            }
        }
        private global::System.String _distinction;
        partial void OndistinctionChanging(global::System.String value);
        partial void OndistinctionChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> prixDGI
        {
            get
            {
                return _prixDGI;
            }
            set
            {
                OnprixDGIChanging(value);
                ReportPropertyChanging("prixDGI");
                _prixDGI = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("prixDGI");
                OnprixDGIChanged();
            }
        }
        private Nullable<global::System.Double> _prixDGI;
        partial void OnprixDGIChanging(Nullable<global::System.Double> value);
        partial void OnprixDGIChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> prixPorteurProjet
        {
            get
            {
                return _prixPorteurProjet;
            }
            set
            {
                OnprixPorteurProjetChanging(value);
                ReportPropertyChanging("prixPorteurProjet");
                _prixPorteurProjet = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("prixPorteurProjet");
                OnprixPorteurProjetChanged();
            }
        }
        private Nullable<global::System.Double> _prixPorteurProjet;
        partial void OnprixPorteurProjetChanging(Nullable<global::System.Double> value);
        partial void OnprixPorteurProjetChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> surfacePlache
        {
            get
            {
                return _surfacePlache;
            }
            set
            {
                OnsurfacePlacheChanging(value);
                ReportPropertyChanging("surfacePlache");
                _surfacePlache = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("surfacePlache");
                OnsurfacePlacheChanged();
            }
        }
        private Nullable<global::System.Double> _surfacePlache;
        partial void OnsurfacePlacheChanging(Nullable<global::System.Double> value);
        partial void OnsurfacePlacheChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> surfaceVentable
        {
            get
            {
                return _surfaceVentable;
            }
            set
            {
                OnsurfaceVentableChanging(value);
                ReportPropertyChanging("surfaceVentable");
                _surfaceVentable = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("surfaceVentable");
                OnsurfaceVentableChanged();
            }
        }
        private Nullable<global::System.Double> _surfaceVentable;
        partial void OnsurfaceVentableChanging(Nullable<global::System.Double> value);
        partial void OnsurfaceVentableChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> surfaceVoirie
        {
            get
            {
                return _surfaceVoirie;
            }
            set
            {
                OnsurfaceVoirieChanging(value);
                ReportPropertyChanging("surfaceVoirie");
                _surfaceVoirie = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("surfaceVoirie");
                OnsurfaceVoirieChanged();
            }
        }
        private Nullable<global::System.Double> _surfaceVoirie;
        partial void OnsurfaceVoirieChanging(Nullable<global::System.Double> value);
        partial void OnsurfaceVoirieChanged();

        #endregion

    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Projet2Model", "FK__construct__codeP__0DAF0CB0", "construction")]
        public EntityCollection<construction> construction
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<construction>("Projet2Model.FK__construct__codeP__0DAF0CB0", "construction");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<construction>("Projet2Model.FK__construct__codeP__0DAF0CB0", "construction", value);
                }
            }
        }
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Projet2Model", "FK__foncier__codePro__08EA5793", "foncier")]
        public EntityCollection<foncier> foncier
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<foncier>("Projet2Model.FK__foncier__codePro__08EA5793", "foncier");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<foncier>("Projet2Model.FK__foncier__codePro__08EA5793", "foncier", value);
                }
            }
        }
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Projet2Model", "FK__resultat__codePr__3B75D760", "resultat")]
        public EntityCollection<resultat> resultat
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<resultat>("Projet2Model.FK__resultat__codePr__3B75D760", "resultat");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<resultat>("Projet2Model.FK__resultat__codePr__3B75D760", "resultat", value);
                }
            }
        }
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Projet2Model", "FK__viabilisa__codeP__1273C1CD", "viabilisation")]
        public EntityCollection<viabilisation> viabilisation
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<viabilisation>("Projet2Model.FK__viabilisa__codeP__1273C1CD", "viabilisation");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<viabilisation>("Projet2Model.FK__viabilisa__codeP__1273C1CD", "viabilisation", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Projet2Model", Name="foncier")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class foncier : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet foncier.
        /// </summary>
        /// <param name="numfoncier">Valeur initiale de la propriété numfoncier.</param>
        public static foncier Createfoncier(global::System.Int32 numfoncier)
        {
            foncier foncier = new foncier();
            foncier.numfoncier = numfoncier;
            return foncier;
        }

        #endregion

        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 numfoncier
        {
            get
            {
                return _numfoncier;
            }
            set
            {
                if (_numfoncier != value)
                {
                    OnnumfoncierChanging(value);
                    ReportPropertyChanging("numfoncier");
                    _numfoncier = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("numfoncier");
                    OnnumfoncierChanged();
                }
            }
        }
        private global::System.Int32 _numfoncier;
        partial void OnnumfoncierChanging(global::System.Int32 value);
        partial void OnnumfoncierChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> superficieterrain
        {
            get
            {
                return _superficieterrain;
            }
            set
            {
                OnsuperficieterrainChanging(value);
                ReportPropertyChanging("superficieterrain");
                _superficieterrain = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("superficieterrain");
                OnsuperficieterrainChanged();
            }
        }
        private Nullable<global::System.Double> _superficieterrain;
        partial void OnsuperficieterrainChanging(Nullable<global::System.Double> value);
        partial void OnsuperficieterrainChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> enregistrementcf
        {
            get
            {
                return _enregistrementcf;
            }
            set
            {
                OnenregistrementcfChanging(value);
                ReportPropertyChanging("enregistrementcf");
                _enregistrementcf = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("enregistrementcf");
                OnenregistrementcfChanged();
            }
        }
        private Nullable<global::System.Double> _enregistrementcf;
        partial void OnenregistrementcfChanging(Nullable<global::System.Double> value);
        partial void OnenregistrementcfChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> notaire
        {
            get
            {
                return _notaire;
            }
            set
            {
                OnnotaireChanging(value);
                ReportPropertyChanging("notaire");
                _notaire = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("notaire");
                OnnotaireChanged();
            }
        }
        private Nullable<global::System.Double> _notaire;
        partial void OnnotaireChanging(Nullable<global::System.Double> value);
        partial void OnnotaireChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> tpi
        {
            get
            {
                return _tpi;
            }
            set
            {
                OntpiChanging(value);
                ReportPropertyChanging("tpi");
                _tpi = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("tpi");
                OntpiChanged();
            }
        }
        private Nullable<global::System.Double> _tpi;
        partial void OntpiChanging(Nullable<global::System.Double> value);
        partial void OntpiChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> codeProjet
        {
            get
            {
                return _codeProjet;
            }
            set
            {
                OncodeProjetChanging(value);
                ReportPropertyChanging("codeProjet");
                _codeProjet = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("codeProjet");
                OncodeProjetChanged();
            }
        }
        private Nullable<global::System.Int32> _codeProjet;
        partial void OncodeProjetChanging(Nullable<global::System.Int32> value);
        partial void OncodeProjetChanged();

        #endregion

    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Projet2Model", "FK__foncier__codePro__08EA5793", "ficheProjet")]
        public ficheProjet ficheProjet
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ficheProjet>("Projet2Model.FK__foncier__codePro__08EA5793", "ficheProjet").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ficheProjet>("Projet2Model.FK__foncier__codePro__08EA5793", "ficheProjet").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ficheProjet> ficheProjetReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ficheProjet>("Projet2Model.FK__foncier__codePro__08EA5793", "ficheProjet");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ficheProjet>("Projet2Model.FK__foncier__codePro__08EA5793", "ficheProjet", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Projet2Model", Name="resultat")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class resultat : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet resultat.
        /// </summary>
        /// <param name="numresultat">Valeur initiale de la propriété numresultat.</param>
        public static resultat Createresultat(global::System.Int32 numresultat)
        {
            resultat resultat = new resultat();
            resultat.numresultat = numresultat;
            return resultat;
        }

        #endregion

        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 numresultat
        {
            get
            {
                return _numresultat;
            }
            set
            {
                if (_numresultat != value)
                {
                    OnnumresultatChanging(value);
                    ReportPropertyChanging("numresultat");
                    _numresultat = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("numresultat");
                    OnnumresultatChanged();
                }
            }
        }
        private global::System.Int32 _numresultat;
        partial void OnnumresultatChanging(global::System.Int32 value);
        partial void OnnumresultatChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> TreeainTf
        {
            get
            {
                return _TreeainTf;
            }
            set
            {
                OnTreeainTfChanging(value);
                ReportPropertyChanging("TreeainTf");
                _TreeainTf = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TreeainTf");
                OnTreeainTfChanged();
            }
        }
        private Nullable<global::System.Double> _TreeainTf;
        partial void OnTreeainTfChanging(Nullable<global::System.Double> value);
        partial void OnTreeainTfChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> EnregistrementCF
        {
            get
            {
                return _EnregistrementCF;
            }
            set
            {
                OnEnregistrementCFChanging(value);
                ReportPropertyChanging("EnregistrementCF");
                _EnregistrementCF = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EnregistrementCF");
                OnEnregistrementCFChanged();
            }
        }
        private Nullable<global::System.Double> _EnregistrementCF;
        partial void OnEnregistrementCFChanging(Nullable<global::System.Double> value);
        partial void OnEnregistrementCFChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Notaire
        {
            get
            {
                return _Notaire;
            }
            set
            {
                OnNotaireChanging(value);
                ReportPropertyChanging("Notaire");
                _Notaire = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Notaire");
                OnNotaireChanged();
            }
        }
        private Nullable<global::System.Double> _Notaire;
        partial void OnNotaireChanging(Nullable<global::System.Double> value);
        partial void OnNotaireChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> TPI
        {
            get
            {
                return _TPI;
            }
            set
            {
                OnTPIChanging(value);
                ReportPropertyChanging("TPI");
                _TPI = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TPI");
                OnTPIChanged();
            }
        }
        private Nullable<global::System.Double> _TPI;
        partial void OnTPIChanging(Nullable<global::System.Double> value);
        partial void OnTPIChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Somme
        {
            get
            {
                return _Somme;
            }
            set
            {
                OnSommeChanging(value);
                ReportPropertyChanging("Somme");
                _Somme = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Somme");
                OnSommeChanged();
            }
        }
        private Nullable<global::System.Double> _Somme;
        partial void OnSommeChanging(Nullable<global::System.Double> value);
        partial void OnSommeChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> viabilisation
        {
            get
            {
                return _viabilisation;
            }
            set
            {
                OnviabilisationChanging(value);
                ReportPropertyChanging("viabilisation");
                _viabilisation = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("viabilisation");
                OnviabilisationChanged();
            }
        }
        private Nullable<global::System.Double> _viabilisation;
        partial void OnviabilisationChanging(Nullable<global::System.Double> value);
        partial void OnviabilisationChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> ConstructionLogSR3
        {
            get
            {
                return _ConstructionLogSR3;
            }
            set
            {
                OnConstructionLogSR3Changing(value);
                ReportPropertyChanging("ConstructionLogSR3");
                _ConstructionLogSR3 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ConstructionLogSR3");
                OnConstructionLogSR3Changed();
            }
        }
        private Nullable<global::System.Double> _ConstructionLogSR3;
        partial void OnConstructionLogSR3Changing(Nullable<global::System.Double> value);
        partial void OnConstructionLogSR3Changed();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> constructionEquipePR1
        {
            get
            {
                return _constructionEquipePR1;
            }
            set
            {
                OnconstructionEquipePR1Changing(value);
                ReportPropertyChanging("constructionEquipePR1");
                _constructionEquipePR1 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("constructionEquipePR1");
                OnconstructionEquipePR1Changed();
            }
        }
        private Nullable<global::System.Double> _constructionEquipePR1;
        partial void OnconstructionEquipePR1Changing(Nullable<global::System.Double> value);
        partial void OnconstructionEquipePR1Changed();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> CconstructionEquipePR2
        {
            get
            {
                return _CconstructionEquipePR2;
            }
            set
            {
                OnCconstructionEquipePR2Changing(value);
                ReportPropertyChanging("CconstructionEquipePR2");
                _CconstructionEquipePR2 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CconstructionEquipePR2");
                OnCconstructionEquipePR2Changed();
            }
        }
        private Nullable<global::System.Double> _CconstructionEquipePR2;
        partial void OnCconstructionEquipePR2Changing(Nullable<global::System.Double> value);
        partial void OnCconstructionEquipePR2Changed();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> FraisGenereux
        {
            get
            {
                return _FraisGenereux;
            }
            set
            {
                OnFraisGenereuxChanging(value);
                ReportPropertyChanging("FraisGenereux");
                _FraisGenereux = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FraisGenereux");
                OnFraisGenereuxChanged();
            }
        }
        private Nullable<global::System.Double> _FraisGenereux;
        partial void OnFraisGenereuxChanging(Nullable<global::System.Double> value);
        partial void OnFraisGenereuxChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> SommeTotal
        {
            get
            {
                return _SommeTotal;
            }
            set
            {
                OnSommeTotalChanging(value);
                ReportPropertyChanging("SommeTotal");
                _SommeTotal = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SommeTotal");
                OnSommeTotalChanged();
            }
        }
        private Nullable<global::System.Double> _SommeTotal;
        partial void OnSommeTotalChanging(Nullable<global::System.Double> value);
        partial void OnSommeTotalChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String username
        {
            get
            {
                return _username;
            }
            set
            {
                OnusernameChanging(value);
                ReportPropertyChanging("username");
                _username = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("username");
                OnusernameChanged();
            }
        }
        private global::System.String _username;
        partial void OnusernameChanging(global::System.String value);
        partial void OnusernameChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> codeProjet
        {
            get
            {
                return _codeProjet;
            }
            set
            {
                OncodeProjetChanging(value);
                ReportPropertyChanging("codeProjet");
                _codeProjet = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("codeProjet");
                OncodeProjetChanged();
            }
        }
        private Nullable<global::System.Int32> _codeProjet;
        partial void OncodeProjetChanging(Nullable<global::System.Int32> value);
        partial void OncodeProjetChanged();

        #endregion

    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Projet2Model", "FK__resultat__codePr__3B75D760", "ficheProjet")]
        public ficheProjet ficheProjet
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ficheProjet>("Projet2Model.FK__resultat__codePr__3B75D760", "ficheProjet").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ficheProjet>("Projet2Model.FK__resultat__codePr__3B75D760", "ficheProjet").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ficheProjet> ficheProjetReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ficheProjet>("Projet2Model.FK__resultat__codePr__3B75D760", "ficheProjet");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ficheProjet>("Projet2Model.FK__resultat__codePr__3B75D760", "ficheProjet", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Projet2Model", Name="sysdiagrams")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagrams : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet sysdiagrams.
        /// </summary>
        /// <param name="name">Valeur initiale de la propriété name.</param>
        /// <param name="principal_id">Valeur initiale de la propriété principal_id.</param>
        /// <param name="diagram_id">Valeur initiale de la propriété diagram_id.</param>
        public static sysdiagrams Createsysdiagrams(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagrams sysdiagrams = new sysdiagrams();
            sysdiagrams.name = name;
            sysdiagrams.principal_id = principal_id;
            sysdiagrams.diagram_id = diagram_id;
            return sysdiagrams;
        }

        #endregion

        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion

    
    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Projet2Model", Name="Users")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Users : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet Users.
        /// </summary>
        /// <param name="id">Valeur initiale de la propriété ID.</param>
        public static Users CreateUsers(global::System.Int32 id)
        {
            Users users = new Users();
            users.ID = id;
            return users;
        }

        #endregion

        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nom
        {
            get
            {
                return _Nom;
            }
            set
            {
                OnNomChanging(value);
                ReportPropertyChanging("Nom");
                _Nom = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nom");
                OnNomChanged();
            }
        }
        private global::System.String _Nom;
        partial void OnNomChanging(global::System.String value);
        partial void OnNomChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Adress
        {
            get
            {
                return _Adress;
            }
            set
            {
                OnAdressChanging(value);
                ReportPropertyChanging("Adress");
                _Adress = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Adress");
                OnAdressChanged();
            }
        }
        private global::System.String _Adress;
        partial void OnAdressChanging(global::System.String value);
        partial void OnAdressChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Pass
        {
            get
            {
                return _Pass;
            }
            set
            {
                OnPassChanging(value);
                ReportPropertyChanging("Pass");
                _Pass = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Pass");
                OnPassChanged();
            }
        }
        private global::System.String _Pass;
        partial void OnPassChanging(global::System.String value);
        partial void OnPassChanged();

        #endregion

    
    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Projet2Model", Name="viabilisation")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class viabilisation : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet viabilisation.
        /// </summary>
        /// <param name="numviabilisation">Valeur initiale de la propriété numviabilisation.</param>
        public static viabilisation Createviabilisation(global::System.Int32 numviabilisation)
        {
            viabilisation viabilisation = new viabilisation();
            viabilisation.numviabilisation = numviabilisation;
            return viabilisation;
        }

        #endregion

        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 numviabilisation
        {
            get
            {
                return _numviabilisation;
            }
            set
            {
                if (_numviabilisation != value)
                {
                    OnnumviabilisationChanging(value);
                    ReportPropertyChanging("numviabilisation");
                    _numviabilisation = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("numviabilisation");
                    OnnumviabilisationChanged();
                }
            }
        }
        private global::System.Int32 _numviabilisation;
        partial void OnnumviabilisationChanging(global::System.Int32 value);
        partial void OnnumviabilisationChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> pont
        {
            get
            {
                return _pont;
            }
            set
            {
                OnpontChanging(value);
                ReportPropertyChanging("pont");
                _pont = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("pont");
                OnpontChanged();
            }
        }
        private Nullable<global::System.Double> _pont;
        partial void OnpontChanging(Nullable<global::System.Double> value);
        partial void OnpontChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> fosse
        {
            get
            {
                return _fosse;
            }
            set
            {
                OnfosseChanging(value);
                ReportPropertyChanging("fosse");
                _fosse = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fosse");
                OnfosseChanged();
            }
        }
        private Nullable<global::System.Double> _fosse;
        partial void OnfosseChanging(Nullable<global::System.Double> value);
        partial void OnfosseChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> chateauD
        {
            get
            {
                return _chateauD;
            }
            set
            {
                OnchateauDChanging(value);
                ReportPropertyChanging("chateauD");
                _chateauD = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("chateauD");
                OnchateauDChanged();
            }
        }
        private Nullable<global::System.Double> _chateauD;
        partial void OnchateauDChanging(Nullable<global::System.Double> value);
        partial void OnchateauDChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> codeProjet
        {
            get
            {
                return _codeProjet;
            }
            set
            {
                OncodeProjetChanging(value);
                ReportPropertyChanging("codeProjet");
                _codeProjet = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("codeProjet");
                OncodeProjetChanged();
            }
        }
        private Nullable<global::System.Int32> _codeProjet;
        partial void OncodeProjetChanging(Nullable<global::System.Int32> value);
        partial void OncodeProjetChanged();

        #endregion

    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Projet2Model", "FK__viabilisa__codeP__1273C1CD", "ficheProjet")]
        public ficheProjet ficheProjet
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ficheProjet>("Projet2Model.FK__viabilisa__codeP__1273C1CD", "ficheProjet").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ficheProjet>("Projet2Model.FK__viabilisa__codeP__1273C1CD", "ficheProjet").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ficheProjet> ficheProjetReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ficheProjet>("Projet2Model.FK__viabilisa__codeP__1273C1CD", "ficheProjet");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ficheProjet>("Projet2Model.FK__viabilisa__codeP__1273C1CD", "ficheProjet", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
